name: Commit bottles to PR

on:
  pull_request_target:
    types:
      - labeled

jobs:
  bottle:
    name: bottle:command
    if: ${{ contains(github.event.pull_request.labels.*.name, '!add-bottles') && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write
      pull-requests: write
    # This job both checks out PR code and has write permissions. Do not remove the check against foreign PRs.
    # On the off chance we start accepting third-party contributions, we'll need a different two-PR strategy.
    steps:
      - name: Remove command label
        run: gh pr edit "$PULL_REQUEST" --repo "$GITHUB_REPOSITORY" --remove-label "!add-bottles"
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure PR is ready
        run: |
          pr_status=$(gh pr view "$PULL_REQUEST" --repo "$GITHUB_REPOSITORY" --json state,labels,statusCheckRollup)
          if ! jq -e '.state == "OPEN"' <<< "$pr_status"; then
            echo "Pull request was closed or merged"
            exit 1
          fi
          if ! jq -e '(.labels | map(.name)) | index("merge-without-publishing") == null' <<< "$pr_status"; then
            echo "Pull request has 'merge-without-publishing' label"
            exit 1
          fi
          if ! jq -e '
            (
              .statusCheckRollup
              | map(select(
                (
                  .status != "COMPLETED"
                  and .name != "bottle:command"
                )
                or (
                  (.name | contains(":required"))
                  and .name != "confirm-publish:required"
                  and .conclusion != "SUCCESS"
                )
              ))
            ) | length == 0' <<< "$pr_status"
          then
            echo "Pull request has pending status checks"
            exit 1
          fi
          required_checks=$(jq -c '[.statusCheckRollup[].name | select(. | contains(":required"))]' <<< "$pr_status" | sort | uniq)
          {
            echo "REQUIRED_CHECKS<<EOF"
            echo "$required_checks"
            echo "EOF"
          } >> "$GITHUB_ENV"
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          gh pr checkout "$PULL_REQUEST" --repo "$GITHUB_REPOSITORY"
          pr_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "PR_BRANCH=$pr_branch" >> "$GITHUB_ENV"
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull bottles
        id: pull
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          GITHUB_SHA="$(git merge-base main HEAD)" \
            brew pr-pull --debug \
            --tap="$GITHUB_REPOSITORY" \
            --branch-okay "$PULL_REQUEST" \
            --no-cherry-pick \
            --no-upload \
            --clean \
            --retain-bottle-dir

      - name: Create commits
        run: |
          cd "$BOTTLE_DIR" || exit 1
          brew bottle --merge --write --debug ./*.bottle.json
          new_head=$(git rev-parse HEAD)
          echo "NEW_HEAD=$new_head" >> "$GITHUB_ENV"
        env:
          BOTTLE_DIR: ${{ steps.pull.outputs.bottle_path }}

      - name: Push commits
        uses: Homebrew/actions/git-try-push@main
        with:
          branch: "${{ env.PR_BRANCH }}"
          tries: 5

      - name: Add label
        run: |
          gh pr edit "$PULL_REQUEST" --repo "$GITHUB_REPOSITORY" --add-label "publish-to-tap"
        env:
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assert the required checks pass
        uses: actions/github-script@v8
        with:
          script: |
            for (const check of JSON.parse(process.env.REQUIRED_CHECKS)) {
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: check,
                head_sha: process.env.NEW_HEAD,
                status: 'completed',
                conclusion: 'success'
              });
            }
